// scripts/buildWordBank.mjs
// Run with: node scripts/buildWordBank.mjs

import fs from 'fs';
import path from 'path';
import https from 'https';

const SOURCES = [
  'https://raw.githubusercontent.com/Maximus-/Wordlists/master/GRE.txt',
  'https://raw.githubusercontent.com/dwyl/english-words/master/words_alpha.txt',
];

const OUT_FILE = path.join(process.cwd(), 'src', 'data', 'wordBank.ts');

function fetchText(url) {
  return new Promise((resolve, reject) => {
    https.get(url, (res) => {
      if (res.statusCode !== 200) {
        return reject(new Error(`Failed ${url}: ${res.statusCode}`));
      }
      let data = '';
      res.on('data', (chunk) => (data += chunk));
      res.on('end', () => resolve(data));
    }).on('error', reject);
  });
}

async function main() {
  console.log('📥 Downloading GRE word list...');

  let words = [];

  try {
    const text = await fetchText(SOURCES[0]);
    words = text
      .split(/\r?\n/)
      .map((w) => w.trim().toLowerCase())
      .filter((w) => /^[a-z]{3,15}$/.test(w));
    console.log(`✓ Got ${words.length} words from primary source`);
  } catch (err) {
    console.warn('⚠ Primary source failed, falling back to large dictionary...');
    const text = await fetchText(SOURCES[1]);
    const all = text
      .split(/\r?\n/)
      .map((w) => w.trim().toLowerCase())
      .filter((w) => /^[a-z]{5,12}$/.test(w));
    words = shuffle(all).slice(0, 5000);
    console.log(`✓ Got ${words.length} sampled words from fallback`);
  }

  words = Array.from(new Set(words)).sort();
  if (words.length > 5000) words = words.slice(0, 5000);

  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });

  const content = `// ──────────────────────────────────────────────
//  LexiQ — Curated Word Bank (${words.length} words)
//  Auto-generated by scripts/buildWordBank.mjs
//  DO NOT EDIT MANUALLY
// ──────────────────────────────────────────────

export const WORD_BANK: readonly string[] = ${JSON.stringify(words, null, 2)} as const;

export const WORD_BANK_SIZE = ${words.length};
`;

  fs.writeFileSync(OUT_FILE, content, 'utf8');
  console.log(`✅ Wrote ${words.length} words to ${OUT_FILE}`);
}

function shuffle(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

main().catch((err) => {
  console.error('❌ Failed:', err.message);
  process.exit(1);
});